### ISSUE TITLE
[BUG]: Can't add Gotify instance "Internal Connection error, failed please check your console"

### ISSUE THREAD

**Issue by spinnaker1** [activepieces/activepieces#2746]
**Describe the bug**
When adding a Gotify instance, it fails with "Internal Connection error, failed please check your console.". The Gotify instance is behind Cloudflare (Cloudflare Tunnel) and reachable at a URL like this `https://gotify.spinnakersserver.com/`

activepieces container log:
```
2023-09-19T23:29:54.403379158Z 55687/09/05 04:26AM 30 | pid=8 hostname=fa2fd8d28b0d reqId=req-1h req={"method":"POST","url":"/v1/flows/cSqGWkPJ3m8vyorIUMWMx","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":58860} msg=incoming request 
2023-09-19T23:29:54.454666477Z 55687/09/05 04:27AM 30 | pid=8 hostname=fa2fd8d28b0d reqId=req-1h res={"statusCode":200} responseTime=51.017478942871094 msg=request completed 
2023-09-19T23:30:12.099278800Z 55687/09/05 09:21AM 30 | pid=8 hostname=fa2fd8d28b0d reqId=req-1i req={"method":"POST","url":"/v1/app-connections","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":34496} msg=incoming request 
2023-09-19T23:30:12.171169567Z 55687/09/05 09:22AM 30 | pid=8 hostname=fa2fd8d28b0d msg=Preparing sandbox number 0 for G8qVX3Q54r2TJyEMwgqwO:@activepieces/piece-gotify:0.3.0 
2023-09-19T23:30:12.172491404Z (node:8) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
2023-09-19T23:30:12.172525004Z (Use `node --trace-deprecation ...` to show where the warning was created)
2023-09-19T23:30:12.173471523Z 55687/09/05 09:22AM 30 | pid=8 hostname=fa2fd8d28b0d msg=[PackageManager#executePnpm] directory: /usr/src/app/dist/sandbox/0, fullCommand: npx pnpm init  
2023-09-19T23:30:13.553731616Z 55687/09/05 09:45AM 30 | pid=8 hostname=fa2fd8d28b0d msg=[PackageManager#executePnpm] directory: /usr/src/app/dist/sandbox/0, fullCommand: npx pnpm add @activepieces/piece-gotify-0.3.0@npm:@activepieces/piece-gotify@0.3.0 --prefer-offline --config.lockfile=false --config.auto-install-peers=true 
2023-09-19T23:30:19.535843899Z 55687/09/05 11:25AM 30 | pid=8 hostname=fa2fd8d28b0d msg=sandbox, command: cd /usr/src/app/dist/sandbox/0 && env -i AP_ENVIRONMENT=prod NODE_OPTIONS='--enable-source-maps' /usr/local/bin/node main.js EXECUTE_VALIDATE_AUTH 
2023-09-19T23:30:19.927573678Z 55687/09/05 11:32AM 30 | pid=8 hostname=fa2fd8d28b0d msg=[errorHandler]: 
2023-09-19T23:30:20.089422862Z 55687/09/05 11:32AM 50 | pid=8 hostname=fa2fd8d28b0d err={"type":"RangeError","message":"Invalid key length","stack":"RangeError: Invalid key length\n    at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)\n    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)\n    at new Cipheriv (node:internal/crypto/cipher:249:3)\n    at Object.createCipheriv (node:crypto:141:10)\n    at encryptObject (webpack:///src/app/helper/encryption.ts:49:27)\n    at AppConnectionService.<anonymous> (webpack:///src/app/app-connection/app-connection-service/app-connection-service.ts:54:55)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/packages/backend/node_modules/tslib/tslib.js:166:62)","code":"ERR_CRYPTO_INVALID_KEYLEN"} msg=Invalid key length 
2023-09-19T23:30:20.089464902Z 55687/09/05 11:34AM 50 | pid=8 hostname=fa2fd8d28b0d reqId=req-1i req={"method":"POST","url":"/v1/app-connections","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":34496} res={"statusCode":500} err={"type":"RangeError","message":"Invalid key length","stack":"RangeError: Invalid key length\n    at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)\n    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)\n    at new Cipheriv (node:internal/crypto/cipher:249:3)\n    at Object.createCipheriv (node:crypto:141:10)\n    at encryptObject (webpack:///src/app/helper/encryption.ts:49:27)\n    at AppConnectionService.<anonymous> (webpack:///src/app/app-connection/app-connection-service/app-connection-service.ts:54:55)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/packages/backend/node_modules/tslib/tslib.js:166:62)","code":"ERR_CRYPTO_INVALID_KEYLEN"} msg=Invalid key length 
2023-09-19T23:30:20.089472822Z 55687/09/05 11:34AM 30 | pid=8 hostname=fa2fd8d28b0d reqId=req-1i res={"statusCode":500} responseTime=7991.844982147217 msg=request completed 
```

**To Reproduce**
1. Create Youtube piece with any youtube channel url
2. Create a Gotify piece and try add the Gotify Instance
3. Click "Save"

**Expected behavior**
Gotify instance should be added without errors.

**Additional context**
Using the HTTP POST piece to send a message via the Gotify instance works as normal.

**Comment by soonann** [comment]
Hi @spinnaker1, I've had this issue previously as well. I believe its an issue with the encryption key `AP_ENCRYPTION_KEY` you're providing through the environment variables.

If you look at the `.env.example` file provided in this repo, you'll see that it recommends you to use the `tools/deploy.sh` to generate those keys.

This is due to the encryption algorithm requiring a key of fixed length (e.g. 32 characters) as its encryption key.

**NOTE:**
Before running the `tools/deploy.sh`, I'd suggest you make a backup of your `.env` file (name it like `.env.bak` or something) if you already have one.
The script generates a `.env` file (using the `.example.env`) in the root directory of your project and will overwrite any existing ones if there are any.

**Comment by spinnaker1** [comment]
> [...] its an issue with the encryption key `AP_ENCRYPTION_KEY` you're providing through the environment variables. If you look at the `.env.example` file provided in this repo, you'll see that it recommends you to use the `tools/deploy.sh` to generate those keys.
> 
> This is due to the encryption algorithm requiring a key of fixed length (e.g. 32 characters) as its encryption key.

This solved the issue.
Thank You!
