### ISSUE TITLE
[BUG]: Migration "StoreCodeInsideFlow1697969398200" still fails

### ISSUE THREAD

**Issue by dennismenken** [activepieces/activepieces#3753]
The fix of #3642 has in my case no effect. I have pulled the new docker image and started with the new image. With the new version 0.18.2 I have still the same error and activepieces does not start properly and does not work anymore.

Here is the excerpt from stdout:

```
postgres      | 2024-01-26 11:28:13.986 UTC [33] ERROR:  syntax error at or near "LIMIT" at character 41
postgres      | 2024-01-26 11:28:13.986 UTC [33] STATEMENT:  SELECT * FROM flow_version WHERE id = ? LIMIT 1
activepieces  | Migration "StoreCodeInsideFlow1697969398200" failed, error: syntax error at or near "LIMIT"
activepieces  | {"level":50,"time":1706268494022,"pid":8,"hostname":"e9041e96a56a","err":{"type":"QueryFailedError","message":"syntax error at or near \"LIMIT\"","stack":"QueryFailedError: syntax error at or near \"LIMIT\"\n    at PostgresQueryRunner.query (/usr/src/app/dist/packages/backend/node_modules/typeorm/driver/src/driver/postgres/PostgresQueryRunner.ts:331:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","query":"SELECT * FROM flow_version WHERE id = ? LIMIT 1","parameters":["jgAmkR8PVkEKkzod1TNW6"],"driverError":{"type":"DatabaseError","message":"syntax error at or near \"LIMIT\"","stack":"error: syntax error at or near \"LIMIT\"\n    at /usr/src/app/dist/packages/backend/node_modules/pg/lib/client.js:526:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at PostgresQueryRunner.query (/usr/src/app/dist/packages/backend/node_modules/typeorm/driver/src/driver/postgres/PostgresQueryRunner.ts:260:25)","length":94,"name":"error","severity":"ERROR","code":"42601","position":"41","file":"scan.l","line":"1176","routine":"scanner_yyerror"},"length":94,"severity":"ERROR","code":"42601","position":"41","file":"scan.l","line":"1176","routine":"scanner_yyerror"},"msg":"[Main#main]"}
```

Best regards,
Dennis

**Comment by abuaboud** [comment]
Another bad pattern :( 

Thank you for reporting, should be fixed in https://github.com/activepieces/activepieces/pull/3758
