### ISSUE TITLE
[BUG]: Pulumi one-click deploy to AWS not setting AP_Encryption_Key or AP_JWT_Secret

### ISSUE THREAD

**Issue by TyceHerrman** [activepieces/activepieces#4623]
**Describe the bug**
When using the Pulumi one-click deploy, values for AP_Encryption_Key and JWT_Secret are not being passed.

**To Reproduce**
Click "Deploy with Pulumi" button on this page: https://www.activepieces.com/docs/install/options/aws
Step through deployment steps, either leaving AP_ENCRYPTION_KEY and AP_JWT_Secret blank (which should generate random values) or explicitly setting the values during deployment steps.

**Expected behavior**
Deployment that passes values for AP_Encryption_KEY and AP_JWT_Secret
 
**Cloudwatch log example (example for the AP_Encryption_Key)**

`{"level":50,"time":1711474632823,"pid":8,"hostname":"ip-##-#-##-##.ec2.internal","err":{"type":"ActivepiecesError","message":"SYSTEM_PROP_INVALID: System property AP_ENCRYPTION_KEY must be defined","stack":"Error: SYSTEM_PROP_INVALID: System property AP_ENCRYPTION_KEY must be defined\n    at /usr/src/app/dist/packages/server/api/main.js:1:160150\n    at Generator.next (<anonymous>)\n    at /usr/src/app/dist/packages/server/api/node_modules/tslib/tslib.js:169:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/usr/src/app/dist/packages/server/api/node_modules/tslib/tslib.js:165:16)\n    at t.loadEncryptionKey (/usr/src/app/dist/packages/server/api/main.js:1:159869)\n    at /usr/src/app/dist/packages/server/api/main.js:1:763759\n    at Generator.next (<anonymous>)\n    at /usr/src/app/dist/packages/server/api/node_modules/tslib/tslib.js:169:75\n    at new Promise (<anonymous>)","error":{"code":"SYSTEM_PROP_INVALID","params":{"prop":"ENCRYPTION_KEY"}}},"msg":"[Main#main]"}`

**Additional context**
Previous unfinished discussion on this: https://community.activepieces.com/t/take-2-accessing-self-hosted-activepieces-deployment-on-aws-using-load-balancer-url/3617

Hopefully @GFoley83, you can help with this! Saw all your work from #2429.

**Comment by GFoley83** [comment]
Just seeing this now sorry @abuaboud. Looks like the pulumi config has been updated since my initial PR. Will take a look this week.
