### ISSUE TITLE
[BUG]: Docker file builds successfully but raises error "Cannot find module '@activepieces/shared'" when testing/running

### ISSUE THREAD

**Issue by coglmn** [activepieces/activepieces#4786]
**Describe the bug**

Two Docker file related issues to report:
 
1) When the provided Dockerfile is used to build the project using 'docker build' it builds successfully. However, when trying to test/run/deploy, it raises the following error:

node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module '@activepieces/shared'
Require stack:
- /usr/src/app/dist/packages/server/api/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at moduleId (webpack:///external%20commonjs%20%22@activepieces/shared%22:1:18)
    at r (webpack:///webpack/bootstrap:19:22)
    at moduleId (webpack:///src/app/database/database-connection.ts:1:1)
    at r (webpack:///webpack/bootstrap:19:22)
    at e (webpack:///src/main.ts:1:1)
    at <anonymous> (webpack:///src/main.ts:93:37) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/dist/packages/server/api/main.js' ]
}

Node.js v18.19.1

2) Another observation/question is that PNPM version that is used in the Docker file (pnpm@7.28.0) does not match the one in package.json ( "pnpm": "8.6.12"). This is maybe an unrelated matter but may create other issues during runtime?

**To Reproduce**

Building the docker image using a standard build command:

sudo DOCKER_BUILDKIT=1 docker build . -t  activcepieces_tag1

it builds successfully

then, running/testing it (it does not make a difference if providing the env file/variables or not):

sudo docker run -it  activcepieces_tag1 

it raises the reported error.

**Expected behavior**
To build and run the project successfully using the provided Docker file.

**Screenshots**
Can be replicated using the above command lines.

**Additional context**
None.

**Comment by abuaboud** [comment]
Hii @coglmn 

Can you try it with at least these environment variables defined here:

https://www.activepieces.com/docs/install/options/docker


and replace the docker image with your tag offline, let me know if that fixes the issue.

**Comment by coglmn** [comment]
Thank you, @abuaboud. I ran it with the environment variables defined in that page. It raises the same error and does not run (removing -d below to see the error): 

sudo docker run -p 8080:80 -v ~/.activepieces:/root/.activepieces -e AP_QUEUE_MODE=MEMORY -e AP_DB_TYPE=SQLITE3 -e AP_FRONTEND_URL="http://localhost:8080" docker_image_tag

Console output:

node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module '@activepieces/shared'
Require stack:
- /usr/src/app/dist/packages/server/api/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at moduleId (webpack:///external%20commonjs%20%22@activepieces/shared%22:1:18)
    at r (webpack:///webpack/bootstrap:19:22)
    at moduleId (webpack:///src/app/database/database-connection.ts:1:1)
    at r (webpack:///webpack/bootstrap:19:22)
    at e (webpack:///src/main.ts:1:1)
    at <anonymous> (webpack:///src/main.ts:93:37) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/dist/packages/server/api/main.js' ]
}

Node.js v18.19.1

**Comment by upbrains-admin** [comment]
An update on this case, which is after pulling the latest version of the code again and building the docker, the issue is resolved. 

Thank you, again.

**Comment by coglmn** [comment]
pulling and testing with the latest version solved the problem. Thank you
