### ISSUE TITLE
[BUG]: Redis "useSSL" not working as expected

### ISSUE THREAD

**Issue by alewis001** [activepieces/activepieces#4857]
**Describe the bug**
In order to disable SSL on the connection to Redis, the `AP_REDIS_USE_SSL` environment variable must be omitted rather than set to `"false"`. If the latter is used, ActivePieces still tries to connect using TLS. 

**To Reproduce**
1. Set all necessary other ActivePieces config for a working installation.
2. Set up Redis server that does not support secure connections.
2. Set redis host, db, etc.
3. Set `AP_REDIS_USE_SSL` env variable to `"false"`
4. Start ActivePieces
5. See the following error messages in the log.

```
[ioredis] Unhandled error event: Error: connect ETIMEDOUT
    at TLSSocket.<anonymous> (/usr/src/app/dist/packages/server/api/node_modules/ioredis/built/Redis.js:170:41)
    at Object.onceWrapper (node:events:631:28)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket.emit (node:domain:489:12)
    at Socket._onTimeout (node:net:598:8)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
...
repeat
...
Error: connect ETIMEDOUT
    at TLSSocket.<anonymous> (/usr/src/app/dist/packages/server/api/node_modules/ioredis/built/Redis.js:170:41)
    at Object.onceWrapper (node:events:631:28)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket.emit (node:domain:489:12)
    at Socket._onTimeout (node:net:598:8)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
...
repeat
...
```

**Expected behavior**
A non-TLS connection to Redis is established when the variable value is `"false"`.

**Additional context**
I _think_ the issue might be on [Line 34 of `redis-connection.ts`](https://github.com/activepieces/activepieces/blob/2a902c9996858b9d7b3c51c5d2afe561d6555703/packages/server/api/src/app/database/redis-connection.ts#L34) (as of 0.26.1). If the value is set to `"false"` then the statement becomes `"false" ? {} : undefined` except in that case the ternary will evaluate "false" as truthy. I admit this is just eyeballing the code, I've not put in any debug to confirm my theory.

This issue was found in a Kubernetes environment but I don't think there was any sort of translation issue of the string vs boolean as the `env` command in the container showed this...
```
> env | grep AP_REDIS_USE_SSL
AP_REDIS_USE_SSL=false
```

**Comment by abuaboud** [comment]
It should be fixed in the next release

**Comment by abuaboud** [comment]
@allcontributors please add @alewis001 for bug

**Comment by alewis001** [comment]
> Thank you so much for detailed report!
> 
> It should be fixed in the next release

No problem, glad to help. I would have contributed a fix but unfortunately my plate is a little full at the moment between work and non-work so I thought it was better to get the bug raised first and then see if it was still open if/when I got an opportunity. 

Thank you for the quick turn around!
