### ISSUE TITLE
[BUG]: Pieces (including code piece) fail to load inline editor

### ISSUE THREAD

**Issue by poster983** [activepieces/activepieces#4867]
**Describe the bug**
After updating from 0.26.1 to 0.27 I can no longer edit my code pieces or use the nice monaco editor when editing the body field in http pieces. 

**To Reproduce**
1. Create a Code or Http Piece
2. Click on code or body or response
3. Nothing happens

**Expected behavior**
I expect for the vscode Monaco editor to show up and allow me to edit.

**Comment by poster983** [comment]
I believe this log in the browser console is related:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at y (nls.ts:53:20)
    at Object.localize (nls.ts:106:10)
    at editorOptions.ts:5743:30
    at s._invokeFactory (loader.js:1135:21)
    at s.complete (loader.js:1155:28)
    at s._onModuleComplete (loader.js:1770:27)
    at s._onModuleComplete (loader.js:1784:61)
    at s._onModuleComplete (loader.js:1784:61)
    at s._resolve (loader.js:1726:10)
    at s.defineModule (loader.js:1406:62)

```

**Comment by poster983** [comment]
Nevermind I had to clear the cache
