### ISSUE TITLE
[BUG]: Cannot publish pieces

### ISSUE THREAD

**Issue by LinusOssmann** [activepieces/activepieces#5055]
**Describe the bug**
I cannot publish any pieces to the community so they can be used on a deployed activepieces instance.
I followed the docs to create a piece and ran into issues with even consistently building the whole application when in dev mode like I mentioned here #5019. When I am only building my pieces and no other pieces it currently seems to be working fine. 
Now when I tried to publish my pieces so I can use them to build flows I ran into the following issue after running:
`npm run publish-piece @xxx/piece-cf-productfeed`

`Error: Cannot find module '@activepieces/pieces-framework' 
 throw new Error(`[publishPiece] piece not found, name=${name}`)
          ^
Error: [publishPiece] piece not found, name=@xxx/piece-cf-productfeed
`

I tried this again in different versions and on different setups, but I could not get the piece to publish.
Full log:

`> activepieces@0.28.0 publish-piece
> npx ts-node tools/scripts/pieces/publish-piece.ts @xxx/piece-cf-productfeed

Error: Cannot find module '@activepieces/pieces-framework'
Require stack:
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/cal-com/src/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/packages/pieces/community/cal-com/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/cal-com/src/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts'
  ]
}
Error: Cannot find module '@activepieces/pieces-framework'
Require stack:
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/data-mapper/src/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/packages/pieces/community/data-mapper/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/data-mapper/src/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts'
  ]
}
Error: Cannot find module '@activepieces/pieces-common'
Require stack:
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/google-sheets/src/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/packages/pieces/community/google-sheets/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/google-sheets/src/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts'
  ]
}
Error: Cannot find module '@activepieces/pieces-framework'
Require stack:
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/common/src/lib/helpers/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/common/src/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/packages/pieces/community/common/src/lib/helpers/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/common/src/lib/helpers/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/common/src/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts'
  ]
}
Error: Cannot find module '@activepieces/shared'
Require stack:
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/framework/src/lib/processors/processors.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/framework/src/lib/property/input/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/framework/src/lib/property/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/framework/src/lib/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/framework/src/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/packages/pieces/community/framework/src/lib/processors/processors.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/framework/src/lib/processors/processors.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/framework/src/lib/property/input/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/framework/src/lib/property/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/framework/src/lib/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/framework/src/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts'
  ]
}
Error: Cannot find module '@activepieces/pieces-framework'
Require stack:
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/schedule/src/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/packages/pieces/community/schedule/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/schedule/src/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts'
  ]
}
Error: Cannot find module '@activepieces/pieces-framework'
Require stack:
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/custom/cf-productfeed/src/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/packages/pieces/custom/cf-productfeed/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/custom/cf-productfeed/src/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts'
  ]
}
Error: Cannot find module '@activepieces/pieces-framework'
Require stack:
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/custom/amazon-paapi/src/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/packages/pieces/custom/amazon-paapi/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/custom/amazon-paapi/src/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts'
  ]
}
Error: Cannot find module '@activepieces/pieces-framework'
Require stack:
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/http/src/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/packages/pieces/community/http/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/http/src/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts'
  ]
}
Error: Cannot find module '@activepieces/pieces-framework'
Require stack:
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/math-helper/src/index.js
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts
- [...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/packages/pieces/community/math-helper/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/dist/packages/pieces/community/math-helper/src/index.js',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/utils/piece-script-utils.ts',
    '[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts'
  ]
}
[...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts:12
    throw new Error(`[publishPiece] piece not found, name=${name}`)
          ^
Error: [publishPiece] piece not found, name=@xxx/piece-cf-productfeed
    at publishPiece ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-piece.ts:12:11)
    at async main ([...]/product-feed/product-feed-docker/apps/product-feed-activepieces/tools/scripts/pieces/publish-
piece.ts:36:3)`

You can even see in there that it seems to find my piece in the correct folder and tries to resolve the @activepieces/framwork package, so the real issue does not seem to be my piece not being found.

**To Reproduce**
1. Clone repo
2. Create a piece
3. run npm run publish-piece <your-piece-pkg-name>

**Expected behavior**
The piece should be published.

**Screenshots**

**Additional context**

**Comment by abuaboud** [comment]
Hi @LinusOssmann 

This is now fixed, please sync your fork and try again.
