### ISSUE TITLE
[BUG]: body/password must NOT have more than 25 characters but signup is possible with more than 25 chars

### ISSUE THREAD

**Issue by gandalfb** [activepieces/activepieces#530]
**Describe the bug**
After initial set-up and signup=false I created a user with >25 character password.
The setup was successful and login works.

But after logout and relogin, there is an error that passwords are not allowed >25 chars.

**To Reproduce**
* Start up using docker-compose
* Sign-Up initial user with password >25 characters (incl. special chars)
* See successful login
* Logout
* Login with "normal" login screen
* Receive login error below

**Expected behavior**
Password policy should be consistent accross elements

**Screenshots**
```
-automation-backend-1   |     err: {
-automation-backend-1   |       "type": "Error",
-automation-backend-1   |       "message": "body/password must NOT have more than 25 characters",
-automation-backend-1   |       "stack":
-automation-backend-1   |           Error: body/password must NOT have more than 25 characters
-automation-backend-1   |               at defaultSchemaErrorFormatter (/usr/src/app/node_modules/fastify/lib/context.js:107:10)
-automation-backend-1   |               at wrapValidationError (/usr/src/app/node_modules/fastify/lib/validation.js:131:17)
-automation-backend-1   |               at validate (/usr/src/app/node_modules/fastify/lib/validation.js:111:12)
-automation-backend-1   |               at preValidationCallback (/usr/src/app/node_modules/fastify/lib/handleRequest.js:92:18)
-automation-backend-1   |               at handler (/usr/src/app/node_modules/fastify/lib/handleRequest.js:76:7)
-automation-backend-1   |               at /usr/src/app/node_modules/fastify/lib/contentTypeParser.js:191:9
-automation-backend-1   |               at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
-automation-backend-1   |               at done (/usr/src/app/node_modules/fastify/lib/contentTypeParser.js:185:14)
-automation-backend-1   |               at Parser.defaultJsonParser [as fn] (/usr/src/app/node_modules/fastify/lib/contentTypeParser.js:291:5)
-automation-backend-1   |               at IncomingMessage.onEnd (/usr/src/app/node_modules/fastify/lib/contentTypeParser.js:270:27)
-automation-backend-1   |               at IncomingMessage.emit (node:events:513:28)
-automation-backend-1   |               at endReadableNT (node:internal/streams/readable:1359:12)
-automation-backend-1   |               at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
-automation-backend-1   |       "statusCode": 400,
-automation-backend-1   |       "validation": [
-automation-backend-1   |         {
-automation-backend-1   |           "instancePath": "/password",
-automation-backend-1   |           "schemaPath": "#/properties/password/maxLength",
-automation-backend-1   |           "keyword": "maxLength",
-automation-backend-1   |           "params": {
-automation-backend-1   |             "limit": 25
-automation-backend-1   |           },
-automation-backend-1   |           "message": "must NOT have more than 25 characters"
-automation-backend-1   |         }
```

**Comment by abuaboud** [comment]
Ouch will be fixed in the next release usually happens in Wednesday 

Thank you for reporting that

**Comment by abuaboud** [comment]
Created PR and added to the current sprint, I will close this ticket once it's released.

**Comment by abuaboud** [comment]
Released, Thank you!
