### ISSUE TITLE
[BUG]: Update to 0.30.0 fails due to log migrations

### ISSUE THREAD

**Issue by landonmoir** [activepieces/activepieces#5559]
**Describe the bug**
After upgrading to 0.30.0 activepieces container fails to start. Seems to be something going on with the new log retention feature.
In the past I've run a script every few days to delete old logs, so that may be why its confused.

**To Reproduce**
1. Update from 0.29.1 to 0.30.0

**Crash Dump**
```
Migration "LogFileRelationWithFlowRun1725639666232" failed, error: insert or update on table "flow_run" violates foreign key constraint "fk_flow_run_logs_file_id"

{
  "level": 50,
  "time": 1725985297879,
  "pid": 8,
  "hostname": "86c61b888c82",
  "err": {
    "type": "QueryFailedError",
    "message": "insert or update on table \"flow_run\" violates foreign key constraint \"fk_flow_run_logs_file_id\"",
    "stack": "QueryFailedError: insert or update on table \"flow_run\" violates foreign key constraint \"fk_flow_run_logs_file_id\"\n    at PostgresQueryRunner.query (/usr/src/app/dist/packages/server/api/node_modules/typeorm/driver/src/driver/postgres/PostgresQueryRunner.ts:331:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "query": "\n            ALTER TABLE \"flow_run\"\n            ADD CONSTRAINT \"fk_flow_run_logs_file_id\" FOREIGN KEY (\"logsFileId\") REFERENCES \"file\"(\"id\") ON DELETE\n            SET NULL ON UPDATE NO ACTION\n        ",
    "driverError": {
      "type": "DatabaseError",
      "message": "insert or update on table \"flow_run\" violates foreign key constraint \"fk_flow_run_logs_file_id\"",
      "stack": "error: insert or update on table \"flow_run\" violates foreign key constraint \"fk_flow_run_logs_file_id\"\n    at /usr/src/app/dist/packages/server/api/node_modules/pg/lib/client.js:526:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at PostgresQueryRunner.query (/usr/src/app/dist/packages/server/api/node_modules/typeorm/driver/src/driver/postgres/PostgresQueryRunner.ts:260:25)",
      "length": 282,
      "name": "error",
      "severity": "ERROR",
      "code": "23503",
      "detail": "Key (logsFileId)=(DisEsMjVeAW2asK9MMMFm) is not present in table \"file\".",
      "schema": "public",
      "table": "flow_run",
      "constraint": "fk_flow_run_logs_file_id",
      "file": "ri_triggers.c",
      "line": "2528",
      "routine": "ri_ReportViolation"
    },
    "length": 282,
    "severity": "ERROR",
    "code": "23503",
    "detail": "Key (logsFileId)=(DisEsMjVeAW2asK9MMMFm) is not present in table \"file\".",
    "schema": "public",
    "table": "flow_run",
    "constraint": "fk_flow_run_logs_file_id",
    "file": "ri_triggers.c",
    "line": "2528",
    "routine": "ri_ReportViolation"
  },
  "msg": "[Main#main]"
}
```

**Comment by landonmoir** [comment]
Resolved
I just went into the postgres container and deleted all rows from flow_run that didn't have logs associated with them anymore.
