### ISSUE TITLE
[BUG]: WooCommerce Webhook Registration Fails

### ISSUE THREAD

**Issue by ilovefreesw** [activepieces/activepieces#6090]
**Describe the bug**

**To Reproduce**
1. Create a WooCommerce Connection. Enter the required credentials and website URL.
2. Click on Save and the connection gets created.
3. But the Webhooks fail to register.

In the Docker Logs I can see this:

```
(null, null, \"\\/wp-json\\/wc\\/v3\\/webhooks?__cf_chl_rt_tk=TIsesQsQAf2X9eSi.B7GCKgLLhfFPy51d.cLgvoR8TY-1732110027-1.0.1.1-g9n6tfn._USn_xu8Hr.e5jUbANxe.T6o9dEi32HBGTM\" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>"},"request":{"body":{"name":"Order Created","topic":"order.created","delivery_url":"https://automate.ixxxxxxxs.com/api/v1/webhooks/OcuRULR2PtkcouljdszGV/test"}}}
    at AxiosHttpClient.<anonymous> (/usr/src/app/cache/node_modules/packages/pieces/community/common/src/lib/http/axios/axios-http-client.ts:60:15)
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/cache/node_modules/.pnpm/tslib@1.14.1/node_modules/tslib/tslib.js:113:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  _requestBody: {
    name: 'Order Created',
    topic: 'order.created',
    delivery_url: 'https://automate.ixxxxxxxs.com/api/v1/webhooks/OcuRULR2PtkcouljdszGV/test'
  },
  _err: AxiosError: Request failed with status code 403
      at settle (/usr/src/app/cache/node_modules/.pnpm/axios@1.6.7/node_modules/axios/lib/core/settle.js:19:12)
      at BrotliDecompress.handleStreamEnd (/usr/src/app/cache/node_modules/.pnpm/axios@1.6.7/node_modules/axios/lib/adapters/http.js:589:11)
      at BrotliDecompress.emit (node:events:529:35)
      at endReadableNT (node:internal/streams/readable:1400:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      at Axios.request (/usr/src/app/cache/node_modules/.pnpm/axios@1.6.7/node_modules/axios/lib/core/Axios.js:45:41)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'ERR_BAD_REQUEST',
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'post',
      url: 'https://sulupro.inkliksites.com/wp-json/wc/v3/webhooks',
      params: {},
      data: '{"name":"Order Created","topic":"order.created","delivery_url":"https://automate.inxxxxxxxxs.com/api/v1/webhooks/OcuRULR2PtkcouljdszGV/test"}'
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '141',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'POST /wp-json/wc/v3/webhooks HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Basic Y2tfOWQ5Yjc1ZDgwN2FkODVlMTE1YzllMzdmN2FiN2NlNzZhZGIyOTNmZTpjc19iYWY3ZDUxNTZjZTA3MTY1NmFkNTIzZDEzZDkwYWU2MGU2ODY5MTFh\r\n' +
        'User-Agent: axios/1.6.7\r\n' +
        'Content-Length: 141\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: sulupro.inkliksites.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/wp-json/wc/v3/webhooks',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'sulupro.ixxxxxxxxxs.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    response: {
      status: 403,
      statusText: 'Forbidden',
      headers: [Object [AxiosHeaders]],
      config: [Object],
      request: [ClientRequest],
```
The error is related to BAD REQUEST

**Expected behavior**
A webhook should be registered in the WooCommerce account so that flows can be created.

But it is not working as intended. When click on test, an error is shown.

**Screenshots**
![image](https://github.com/user-attachments/assets/a5e66b20-b64b-46b3-a11e-a69bfcff3c7d)

**Comment by ilovefreesw** [comment]
The webhook doesn't register when we test the order created trigger. But a webhook is created in WooCommerce after the workflow is published.
